version: "3.9"
services:
  server:
    image: cloud.canister.io:5000/miaht94/bulletin-site:latest
    ports:
      - "9000:9000"
    depends_on:
      - mysql
  mysql:
    image: mysql:8.0
    container_name: "mysql-8.0"
    hostname: mysql
    environment:
      - MYSQL_ROOT_PASSWORD=20050910
      - MYSQL_DATABASE=bbs
    command: mysqld --init-file="/docker-entrypoint-initdb.d/init.sql"
    ports:
      - "3306:3306"
    volumes:
      - dbvol:/var/lib/mysql
      - ./mysql-init:/docker-entrypoint-initdb.d
volumes:
  dbvol:
    external: false